### ISSUE TITLE
Because of GPLv3 license simmetrics code can not be used in Apache projects.

### ISSUE THREAD

**Issue by apivovarov** [Simmetrics/simmetrics#5] opened 2015-02-20 19:33 UTC
I plan to add more functions to Apache HIVE and simmetrics code might be very useful.
But "GPLv3 software cannot be included in Apache projects."
http://www.apache.org/licenses/GPL-compatibility.html

Do you think it's possible to release simmetrics under less strict licence?

**Comment by mpkorstanje** [comment] 2015-02-20 20:39
I don't think that will be possible. The original code was written by Sam Chapman and released under the GPLv2 on SourceForge. http://sourceforge.net/projects/simmetrics/

**Comment by jokillsya** [comment] 2015-02-20 20:40
Hi guys.

Yes - I think you're right - I'll change the license.

**Comment by jokillsya** [comment] 2015-02-20 20:42
I work mainly in Vim these days, used to use VimClipse and my config used to generically include V3 of the GPL automatically. I've since switched back to V2.

**Comment by mpkorstanje** [comment] 2015-02-20 20:43
Going back to GPLv2 won't make a difference. "Unless GPLv3 licensors relax this interpretation of their own license regarding linking, our licensing philosophies are fundamentally incompatible. This is an identical issue for both GPLv2 and GPLv3." From the Apache page http://www.apache.org/licenses/GPL-compatibility.html

**Comment by jokillsya** [comment] 2015-02-20 20:45
The issue is not with Apache compatibility in my view - it's more the ability to use the code in closed-source environments. The Classpath Exception should cater for the discrepancies.

**Comment by jokillsya** [comment] 2015-02-20 20:47
http://openjdk.java.net/legal/gplv2+ce.html

**Comment by jokillsya** [comment] 2015-02-20 20:48
Trying to find whether or not this will be sufficient with linking or including code in Apache...

**Comment by jokillsya** [comment] 2015-02-20 20:50
If it's still an issue - I wouldn't mind modifying the license on this Project - I couldn't get hold of Sam Chapman at the time of the port - so I couldn't check...

**Comment by jokillsya** [comment] 2015-02-20 20:56
I think the native C code can be changed at my own discretion since it's so radically different, but I'm not sure if I can move away from a GPL-like license without infringing on Sam Chapman's license...

**Comment by mpkorstanje** [comment] 2015-02-21 00:06
Yeah I'm wondering after how much re-factoring it stops being a derivative. All the new infrastructure is my work and I rewrote these metrics to the point they might as well be a completely new work.

BlockDistance.java
CosineSimilarity.java
DiceSimilarity.java
EuclideanDistance.java
JaccardSimilarity.java
MatchingCoefficient.java
MongeElkan.java
SimonWhite.java

These I didn't do much with, they're clearly Sams

Jaro.java
JaroWinkler.java
Levenshtein.java
NeedlemanWunch.java
OverlapCoefficient.java
SmithWaterman.java
SmithWatermanGotoh.java
SmithWatermanGotohWindowedAffine.java
AffineGap1_1Over3.java
AffineGap5_1.java
AffineGapCost.java
SubCost01.java
SubCost1_Minus2.java
SubCost5_3_Minus3.java
SubstitutionCost.java

**Comment by jokillsya** [comment] 2015-02-21 00:13
Ok - so all of these:

AffineGap1_1Over3.java
AffineGap5_1.java
AffineGapCost.java
SubCost01.java
SubCost1_Minus2.java
SubCost5_3_Minus3.java
SubstitutionCost.java

Are utter crap - meaningless utility stuff to help numbers come out, I got
rid of almost all of them in the C API and replaced them with simple unions
and utility functions. They're not actually metrics at all...

SmithWatermanGotohWindowedAffine.java -> This one just ads a single
parameter to the SmithWatermanGotoh algorithm - which if we're honest - Sam
didn't invent - in fact - the C API totally got rid of his code entirely in
preference to the code in the actual research paper, along with the normal
Smith-Waterman algorithm.

I also re-wrote Jaro, Jaro-Winkler and Levenshtein from scratch - mostly by
digging around research papers and finding optimal C code to replace Sam's
stuff (Which I have a pet hate for if I'm totally honest)...

All of that cost stuff is user preference with a few defaults - it's just a
weighted value that augments the algorithms slightly - same with the
Affines (which is just another buzzword for 'constant that changes the
output slightly')

The so-called overlap-coefficient is just a restatement of a basic Jaccard
similarity with some minor adjustments - buth of which I re-did in the C
API aswell...

As you can probably tell - I spent much more time in the C code than in the
Java...

On Sat, Feb 21, 2015 at 2:06 AM, mpkorstanje <notifications@github.com>
wrote:

> Yeah I'm wondering after how much re-factoring it stops being a
> derivative. All the new infrastructure is my work and I rewrote these
> metrics to the point they might as well be a completely new work.
>
> BlockDistance.java
> CosineSimilarity.java
> DiceSimilarity.java
> EuclideanDistance.java
> JaccardSimilarity.java
> MatchingCoefficient.java
> MongeElkan.java
> SimonWhite.java
>
> These I didn't do much with, they're clearly Sams
>
> Jaro.java
> JaroWinkler.java
> Levenshtein.java
> NeedlemanWunch.java
> OverlapCoefficient.java
> SmithWaterman.java
> SmithWatermanGotoh.java
> SmithWatermanGotohWindowedAffine.java
> AffineGap1_1Over3.java
> AffineGap5_1.java
> AffineGapCost.java
> SubCost01.java
> SubCost1_Minus2.java
> SubCost5_3_Minus3.java
> SubstitutionCost.java
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simmetrics/simmetrics/issues/5#issuecomment-75342322>.
>



-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment] 2015-02-21 00:19
Then...

The C code also includes fully functional implementations of metaphone and
double metaphone - which are very enhanced soundex-like algorithms that are
a lot more accurate since they take language differences into account...

On Sat, Feb 21, 2015 at 2:13 AM, Johnathan Botha <jokillsya@gmail.com>
wrote:

> Ok - so all of these:
>
> AffineGap1_1Over3.java
> AffineGap5_1.java
> AffineGapCost.java
> SubCost01.java
> SubCost1_Minus2.java
> SubCost5_3_Minus3.java
> SubstitutionCost.java
>
> Are utter crap - meaningless utility stuff to help numbers come out, I got
> rid of almost all of them in the C API and replaced them with simple unions
> and utility functions. They're not actually metrics at all...
>
> SmithWatermanGotohWindowedAffine.java -> This one just ads a single
> parameter to the SmithWatermanGotoh algorithm - which if we're honest -
> Sam didn't invent - in fact - the C API totally got rid of his code
> entirely in preference to the code in the actual research paper, along with
> the normal Smith-Waterman algorithm.
>
> I also re-wrote Jaro, Jaro-Winkler and Levenshtein from scratch - mostly
> by digging around research papers and finding optimal C code to replace
> Sam's stuff (Which I have a pet hate for if I'm totally honest)...
>
> All of that cost stuff is user preference with a few defaults - it's just
> a weighted value that augments the algorithms slightly - same with the
> Affines (which is just another buzzword for 'constant that changes the
> output slightly')
>
> The so-called overlap-coefficient is just a restatement of a basic Jaccard
> similarity with some minor adjustments - buth of which I re-did in the C
> API aswell...
>
> As you can probably tell - I spent much more time in the C code than in
> the Java...
>
> On Sat, Feb 21, 2015 at 2:06 AM, mpkorstanje <notifications@github.com>
> wrote:
>
>> Yeah I'm wondering after how much re-factoring it stops being a
>> derivative. All the new infrastructure is my work and I rewrote these
>> metrics to the point they might as well be a completely new work.
>>
>> BlockDistance.java
>> CosineSimilarity.java
>> DiceSimilarity.java
>> EuclideanDistance.java
>> JaccardSimilarity.java
>> MatchingCoefficient.java
>> MongeElkan.java
>> SimonWhite.java
>>
>> These I didn't do much with, they're clearly Sams
>>
>> Jaro.java
>> JaroWinkler.java
>> Levenshtein.java
>> NeedlemanWunch.java
>> OverlapCoefficient.java
>> SmithWaterman.java
>> SmithWatermanGotoh.java
>> SmithWatermanGotohWindowedAffine.java
>> AffineGap1_1Over3.java
>> AffineGap5_1.java
>> AffineGapCost.java
>> SubCost01.java
>> SubCost1_Minus2.java
>> SubCost5_3_Minus3.java
>> SubstitutionCost.java
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Simmetrics/simmetrics/issues/5#issuecomment-75342322>
>> .
>>
>
>
>
> --
> Best Regards
>
> Johnathan Botha
>
>


-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment] 2015-02-21 00:30
I also have a bunch of incomplete implementations sitting in a C project
that I'll spend some time on soon, these include:

* Hamming-Distance
* Damerau-Levenshtein distance
* Mahalanobis distance
* Some of Sorensen's distances
* A whole array of Array and Vector distance metrics used in biological
research (My sister is a geneticist, and use some of these quite often)

On Sat, Feb 21, 2015 at 2:19 AM, Johnathan Botha <jokillsya@gmail.com>
wrote:

> Then...
>
> The C code also includes fully functional implementations of metaphone and
> double metaphone - which are very enhanced soundex-like algorithms that are
> a lot more accurate since they take language differences into account...
>
> On Sat, Feb 21, 2015 at 2:13 AM, Johnathan Botha <jokillsya@gmail.com>
> wrote:
>
>> Ok - so all of these:
>>
>> AffineGap1_1Over3.java
>> AffineGap5_1.java
>> AffineGapCost.java
>> SubCost01.java
>> SubCost1_Minus2.java
>> SubCost5_3_Minus3.java
>> SubstitutionCost.java
>>
>> Are utter crap - meaningless utility stuff to help numbers come out, I
>> got rid of almost all of them in the C API and replaced them with simple
>> unions and utility functions. They're not actually metrics at all...
>>
>> SmithWatermanGotohWindowedAffine.java -> This one just ads a single
>> parameter to the SmithWatermanGotoh algorithm - which if we're honest -
>> Sam didn't invent - in fact - the C API totally got rid of his code
>> entirely in preference to the code in the actual research paper, along with
>> the normal Smith-Waterman algorithm.
>>
>> I also re-wrote Jaro, Jaro-Winkler and Levenshtein from scratch - mostly
>> by digging around research papers and finding optimal C code to replace
>> Sam's stuff (Which I have a pet hate for if I'm totally honest)...
>>
>> All of that cost stuff is user preference with a few defaults - it's just
>> a weighted value that augments the algorithms slightly - same with the
>> Affines (which is just another buzzword for 'constant that changes the
>> output slightly')
>>
>> The so-called overlap-coefficient is just a restatement of a basic
>> Jaccard similarity with some minor adjustments - buth of which I re-did in
>> the C API aswell...
>>
>> As you can probably tell - I spent much more time in the C code than in
>> the Java...
>>
>> On Sat, Feb 21, 2015 at 2:06 AM, mpkorstanje <notifications@github.com>
>> wrote:
>>
>>> Yeah I'm wondering after how much re-factoring it stops being a
>>> derivative. All the new infrastructure is my work and I rewrote these
>>> metrics to the point they might as well be a completely new work.
>>>
>>> BlockDistance.java
>>> CosineSimilarity.java
>>> DiceSimilarity.java
>>> EuclideanDistance.java
>>> JaccardSimilarity.java
>>> MatchingCoefficient.java
>>> MongeElkan.java
>>> SimonWhite.java
>>>
>>> These I didn't do much with, they're clearly Sams
>>>
>>> Jaro.java
>>> JaroWinkler.java
>>> Levenshtein.java
>>> NeedlemanWunch.java
>>> OverlapCoefficient.java
>>> SmithWaterman.java
>>> SmithWatermanGotoh.java
>>> SmithWatermanGotohWindowedAffine.java
>>> AffineGap1_1Over3.java
>>> AffineGap5_1.java
>>> AffineGapCost.java
>>> SubCost01.java
>>> SubCost1_Minus2.java
>>> SubCost5_3_Minus3.java
>>> SubstitutionCost.java
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Simmetrics/simmetrics/issues/5#issuecomment-75342322>
>>> .
>>>
>>
>>
>>
>> --
>> Best Regards
>>
>> Johnathan Botha
>>
>>
>
>
> --
> Best Regards
>
> Johnathan Botha
>
>


-- 
Best Regards

Johnathan Botha

**Comment by mpkorstanje** [comment] 2015-02-21 00:42
Okay I reckon I'll be porting all those from the simmetricslib then.

**Comment by jokillsya** [comment] 2015-02-21 00:44
Let's get your latest dev code merged first, then worry about that...
Besides, your sounded works , we may as well work on porting the megaphone
algorithms first...

**Comment by apivovarov** [comment] 2015-02-21 09:16
I asked on hive dev mail list if GPLv2 software can be included to Apache projects.
Unfortunately no. https://www.mail-archive.com/dev@hive.apache.org/msg111136.html
I checked hive pom xml - most of the dependencies published under Apache v2.0. Some components under BSD license.
Many popular java products (tomcat, jetty, spring, solr, hadoop, derby) published under Apache v2.0

**Comment by jokillsya** [comment] 2015-02-21 10:08
Alright, were having a look at how much of the code has actually been rewritten by me and others to see if we can move to a more permissive license.

I'm able to change the license of the C code easily though...

Sent from my HTC

----- Reply message -----

**Comment by mpkorstanje** [comment] 2015-02-21 12:30
About the dev code, what issues are there right now?

**Comment by jmrozanec** [comment] 2015-08-18 18:23
@apivovarov @mpkorstanje @jokillsya I found the [following repository](https://github.com/TeamCohen/secondstring), which has some implementations of String similarity metrics that already exist at simmetrics, and also provides some other metrics not implemented here. 
Since simmetrics has the licensing issue, a better API and is already present at Maven central, this may be an opportunity to adapt implementations from secondstring and become independent of original simmetrics files licensed under GPL license.

**Comment by mpkorstanje** [comment] 2015-08-18 19:42
Hey jmrozanec, 

I don't believe apivovarov still has a horse in this race. Looking at Hive he has had his own version of cosine similarity implemented a while ago.

I personally do not really consider this a pressing issue. My aim for this project was to practice re-factoring, apply Effective Java in combination with actual releases. That Simmetrics happens to be useful and used is a nice can-trip. That it can't be used in Apache projects is a pity. However the metrics included are rather trivial and well described on Wikipedia. If there is a pressing need for them they can be implemented with ease.

Looking at the SecondString repo makes me rather sad. While it has more metrics, the structure looks to be the same as the original Simmetrics. It includes the same clutter and relies on extending classes to add functionality rather then composing multiple classes together as we're doing now. I'd rather not redesign a second API. I'm also not familiar with the Carnegie Melon licence. 

What I am currently doing is trying to track down Sam Chapman and see if he agrees to more relaxed licence. I feel this would be the right way to do things and it would make the whole discussion moot. The university email seems to be dead and I've had no reaction on his Sourceforge email. I haven't tried finding him on social media yet.

If you're willing to help tracking him down, you'd be most welcome.

**Comment by jmrozanec** [comment] 2015-08-18 22:03
@mpkorstanje thank you for the quick reply!
I agree the license is not a pressing issue, but regardless apivovarov's interest, it would be good to change the license to Apache, since it would help to spread the project to consolidate it as the standard for string metrics in Java.
I agree on your statements about SecondString project. I am also not familiar with the license, but we may raise an issue requesting the authors to change it, as well as invite them to a joint effort porting code to simmetrics. This can also thought as a community effort: we may set a roadmap and open a simmetrics issue requesting community's help to port those metrics once the SecondString license is relaxed.

**Comment by mpkorstanje** [comment] 2015-08-23 13:20
What I'm looking for are well known metrics with either preferably a Wikipedia page or a publicly accessible paper. With that in mind I've given the SecondString project a second look. So far I can find only two metrics that meet those criteria and are not yet included in Simmetrics. These are  the Jensen-Shannon distance and tf-idf. Neither is complicated enough to warrant a port. It would probably be easier and cleaner to use Wikipedia and write them from scratch. It doesn't need much of a roadmap. So I think you can hold off drumming up community support for just a while. However for the long term that would be a good way to grow.

But best work on this licence issue first.

**Comment by mpkorstanje** [comment] 2015-10-17 15:13
As of version 3.2.3 the licence has been changed to Apache Version 2.0.

**Closed by mpkorstanje** 2015-10-17 15:13 UTC

**Comment by mpkorstanje** [comment] 2016-08-10 22:46
@apivovarov you may want to double check the code used in HIVE-9557.

As of v4.0.0. the CosineSimilarity for sets is better described as the Tanimoto coefficient. CosineSimilarity has been changed from SetMetric to MultisetMetric. It will now take token occurrence into account.
